"""some indices added

Revision ID: 92494aff6b58
Revises: d965bcff4ba7
Create Date: 2023-06-22 22:44:20.798892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92494aff6b58'
down_revision = 'd965bcff4ba7'
branch_labels = None
depends_on = None

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_votes_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_votes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_votes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_votes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_subreddit_id'), ['subreddit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_posts_subreddit_id'))

    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_votes_post_id'))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))

    with op.batch_alter_table('comment_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_votes_comment_id'))

    # ### end Alembic commands ###
